"""
Compliance Agent: To make sure the results generated by the Resolution Agent is complaint with the accounting standards and regulations, 
we will use a Compliance Agent to validate the proposed resolution.
As the results are generated by a LLM,  we use deterministic validation rules to validate the proposed resolution. 
"""

from typing import Any, Literal
from pydantic import BaseModel
from agents.resolution_agent import Resolution

class ComplianceVerdict(BaseModel):

    transaction_id : str
    approved_action : Literal[
        "AUTO_RECONCILE",
        "WAIT_FOR_SETTLEMENT",
        "REQUEST_MISSING_DOCUMENT",
        "CREATE_JOURNAL_ENTRY",
        "ESCALATE"
    ]
    is_compliant : bool
    override_reason : str | None = None
    original_resolution_action : str
    confidence : float
    journal_entries : list[dict[str, Any]] | None = None


class ComplianceAgent:
    """
        Complaiance Validation Agent

        Deterministically validates resolution proposals against financial controls:
        - Minimum confidence threshold(0.75)
        - Double-entry bookkeeping balance (Total debit == Total credit)
        -  Allowed Chart of Accounts
        - High risk anomaly safety ovverrides (e.g. CUSTOMER_MISMATCH -> ESCALATE)

    """

    ALLOWED_ACCOUNTS ={
        "1010 Cash",
        "1200 Accounts Receivable",
        "2010 Accounts Payable",
        "5010 Bank Fees & Service Charges",
        "5090 Reconciliation Discrepancies",
        "4000 Revenue"
    }
    

    CONFIDENCE_THRESHOLD = 0.75

    def validate(
            self,
            proposal: Resolution,
            anomaly_result : dict[str, Any] | None = None
    )-> ComplianceVerdict:
        
        original_action = proposal.action
        transaction_id = proposal.transaction_id

        # Rule 1 : High risk anomaly safety Downgrade
        if anomaly_result:
            anomaly_type = anomaly_result.get("anomaly_type","")
            if anomaly_type in ["CUSTOMER_MISMATCH", "CUSTOMER_MISMATCH","BROKEN_REFERENCE"]:
                if original_action != "ESCALATE":
                    return ComplianceVerdict(
                        transaction_id=transaction_id,
                        approved_action="ESCALATE",
                        is_compliant=False,
                        override_reason=f"High risk anomaly detected: {anomaly_type}. Escalating.",
                        original_proposed_action=original_action,
                        confidence=proposal.confidence,
                        journal_entries=None
                    )


        # Rule 2 : Confidence Threshold
        if proposal.confidence < self.CONFIDENCE_THRESHOLD:
            if original_action != "ESCALATE":
                return ComplianceVerdict(
                    transaction_id=transaction_id,
                    approved_action="ESCALATE",
                    is_compliant=False,
                    override_reason=f"Confidence below threshold ({proposal.confidence:.2f} below threshold {self.CONFIDENCE_THRESHOLD}).",
                    original_proposed_action=original_action,
                    confidence=proposal.confidence,
                    journal_entries=None
                )           


        # Rule 3 : Journal Entry Compliance (Balanced Debit/Credit and Allowed Accounts)

        if proposal.action == "CREATE_JOURNAL_ENTRY":
            if not proposal.journal_entries:
                return ComplianceVerdict(
                    transaction_id = transaction_id,
                    approved_action = "ESCALATE",
                    is_compliant = False,
                    override_reason = "Accounting Violation: CREATE_JOURNAL_ENTRY proposed without journal entries.",
                    original_proposed_action = original_action,
                    confidence = proposal.confidence,
                    journal_entries = None
                )

            total_debit = sum(round(entry.debit, 2) for entry in proposal.journal_entries)
            total_credit = sum(round(entry.credit, 2) for entry in proposal.journal_entries)

            if round(total_debit, 2) != round(total_credit, 2):
                return ComplianceVerdict(
                    transaction_id = transaction_id,
                    approved_action = "ESCALATE",
                    is_compliant = False,
                    override_reason = f"Accounting Violation: Unbalanced debits and credits. Total Debit: {total_debit}, Total Credit: {total_credit}.",
                    original_proposed_action = original_action,
                    confidence = proposal.confidence,
                    journal_entries = None
                )

            # Check account validity against allowed accounts list

            for entry in proposal.journal_entries:
                valid_account = any(
                    allowed.lower() in entry.account.lower() or 
                    entry.account.lower() in allowed.lower()
                    for allowed in self.ALLOWED_ACCOUNTS
                )
                if not valid_account:
                    return ComplianceVerdict(
                        transaction_id = transaction_id,
                        approved_action = "ESCALATE",
                        is_compliant = False,
                        override_reason = f"Chart of Accounts Violation: Account '{entry.account}' in journal entries is not allowed.",
                        original_proposed_action = original_action,
                        confidence = proposal.confidence,
                        journal_entries = None
                    )

        # If all checks pass, return the original proposal as compliant
        serialized_entries = (
            [e.model.dump() for e in proposal.journal_entries]
            if proposal.journal_entries else None
        )

        return ComplianceVerdict(
            transaction_id=transaction_id,
            approved_action=original_action,
            is_compliant=True,
            override_reason=None,
            original_resolution_action=original_action,
            confidence=proposal.confidence,
            journal_entries=serialized_entries
        )